---
- name: updating apt
  apt:
          upgrade: yes
          update_cache: yes

- name: installing packages
  apt: 
          name: "{{ item }}"
          state: present
  with_items:
          - apt-transport-https 
          - ca-certificates 
          - curl 
          - software-properties-common

- name: downloading docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: adding key
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present

- name: updating apt
  apt:
          upgrade: yes
          update_cache: yes

- name: Install Docker
  apt: 
           name: docker-ce
           state: present
